/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNetDotNet {

using System;
using System.Runtime.InteropServices;

public class RakNetStatisticsStruct : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RakNetStatisticsStruct(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(RakNetStatisticsStruct obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~RakNetStatisticsStruct() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        RakNetPINVOKE.delete_RakNetStatisticsStruct(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_unsigned_int messageSendBuffer {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_messageSendBuffer_set(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(value));
    } 
    get {
      IntPtr cPtr = RakNetPINVOKE.RakNetStatisticsStruct_messageSendBuffer_get(swigCPtr);
      SWIGTYPE_p_unsigned_int ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_int messagesSent {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_messagesSent_set(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(value));
    } 
    get {
      IntPtr cPtr = RakNetPINVOKE.RakNetStatisticsStruct_messagesSent_get(swigCPtr);
      SWIGTYPE_p_unsigned_int ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_int messageDataBitsSent {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_messageDataBitsSent_set(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(value));
    } 
    get {
      IntPtr cPtr = RakNetPINVOKE.RakNetStatisticsStruct_messageDataBitsSent_get(swigCPtr);
      SWIGTYPE_p_unsigned_int ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_int messageTotalBitsSent {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_messageTotalBitsSent_set(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(value));
    } 
    get {
      IntPtr cPtr = RakNetPINVOKE.RakNetStatisticsStruct_messageTotalBitsSent_get(swigCPtr);
      SWIGTYPE_p_unsigned_int ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
      return ret;
    } 
  }

  public uint packetsContainingOnlyAcknowlegements {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_packetsContainingOnlyAcknowlegements_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_packetsContainingOnlyAcknowlegements_get(swigCPtr);
      return ret;
    } 
  }

  public uint acknowlegementsSent {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_acknowlegementsSent_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_acknowlegementsSent_get(swigCPtr);
      return ret;
    } 
  }

  public uint acknowlegementsPending {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_acknowlegementsPending_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_acknowlegementsPending_get(swigCPtr);
      return ret;
    } 
  }

  public uint acknowlegementBitsSent {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_acknowlegementBitsSent_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_acknowlegementBitsSent_get(swigCPtr);
      return ret;
    } 
  }

  public uint packetsContainingOnlyAcknowlegementsAndResends {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_packetsContainingOnlyAcknowlegementsAndResends_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_packetsContainingOnlyAcknowlegementsAndResends_get(swigCPtr);
      return ret;
    } 
  }

  public uint messageResends {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_messageResends_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_messageResends_get(swigCPtr);
      return ret;
    } 
  }

  public uint messageDataBitsResent {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_messageDataBitsResent_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_messageDataBitsResent_get(swigCPtr);
      return ret;
    } 
  }

  public uint messagesTotalBitsResent {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_messagesTotalBitsResent_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_messagesTotalBitsResent_get(swigCPtr);
      return ret;
    } 
  }

  public uint messagesOnResendQueue {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_messagesOnResendQueue_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_messagesOnResendQueue_get(swigCPtr);
      return ret;
    } 
  }

  public uint numberOfUnsplitMessages {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_numberOfUnsplitMessages_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_numberOfUnsplitMessages_get(swigCPtr);
      return ret;
    } 
  }

  public uint numberOfSplitMessages {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_numberOfSplitMessages_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_numberOfSplitMessages_get(swigCPtr);
      return ret;
    } 
  }

  public uint totalSplits {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_totalSplits_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_totalSplits_get(swigCPtr);
      return ret;
    } 
  }

  public uint packetsSent {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_packetsSent_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_packetsSent_get(swigCPtr);
      return ret;
    } 
  }

  public uint encryptionBitsSent {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_encryptionBitsSent_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_encryptionBitsSent_get(swigCPtr);
      return ret;
    } 
  }

  public uint totalBitsSent {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_totalBitsSent_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_totalBitsSent_get(swigCPtr);
      return ret;
    } 
  }

  public uint sequencedMessagesOutOfOrder {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_sequencedMessagesOutOfOrder_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_sequencedMessagesOutOfOrder_get(swigCPtr);
      return ret;
    } 
  }

  public uint sequencedMessagesInOrder {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_sequencedMessagesInOrder_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_sequencedMessagesInOrder_get(swigCPtr);
      return ret;
    } 
  }

  public uint orderedMessagesOutOfOrder {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_orderedMessagesOutOfOrder_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_orderedMessagesOutOfOrder_get(swigCPtr);
      return ret;
    } 
  }

  public uint orderedMessagesInOrder {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_orderedMessagesInOrder_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_orderedMessagesInOrder_get(swigCPtr);
      return ret;
    } 
  }

  public uint packetsReceived {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_packetsReceived_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_packetsReceived_get(swigCPtr);
      return ret;
    } 
  }

  public uint packetsWithBadCRCReceived {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_packetsWithBadCRCReceived_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_packetsWithBadCRCReceived_get(swigCPtr);
      return ret;
    } 
  }

  public uint bitsReceived {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_bitsReceived_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_bitsReceived_get(swigCPtr);
      return ret;
    } 
  }

  public uint bitsWithBadCRCReceived {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_bitsWithBadCRCReceived_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_bitsWithBadCRCReceived_get(swigCPtr);
      return ret;
    } 
  }

  public uint acknowlegementsReceived {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_acknowlegementsReceived_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_acknowlegementsReceived_get(swigCPtr);
      return ret;
    } 
  }

  public uint duplicateAcknowlegementsReceived {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_duplicateAcknowlegementsReceived_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_duplicateAcknowlegementsReceived_get(swigCPtr);
      return ret;
    } 
  }

  public uint messagesReceived {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_messagesReceived_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_messagesReceived_get(swigCPtr);
      return ret;
    } 
  }

  public uint invalidMessagesReceived {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_invalidMessagesReceived_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_invalidMessagesReceived_get(swigCPtr);
      return ret;
    } 
  }

  public uint duplicateMessagesReceived {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_duplicateMessagesReceived_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_duplicateMessagesReceived_get(swigCPtr);
      return ret;
    } 
  }

  public uint messagesWaitingForReassembly {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_messagesWaitingForReassembly_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_messagesWaitingForReassembly_get(swigCPtr);
      return ret;
    } 
  }

  public uint internalOutputQueueSize {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_internalOutputQueueSize_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_internalOutputQueueSize_get(swigCPtr);
      return ret;
    } 
  }

  public double bitsPerSecond {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_bitsPerSecond_set(swigCPtr, value);
    } 
    get {
      double ret = RakNetPINVOKE.RakNetStatisticsStruct_bitsPerSecond_get(swigCPtr);
      return ret;
    } 
  }

  public uint connectionStartTime {
    set {
      RakNetPINVOKE.RakNetStatisticsStruct_connectionStartTime_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.RakNetStatisticsStruct_connectionStartTime_get(swigCPtr);
      return ret;
    } 
  }

  public RakNetStatisticsStruct() : this(RakNetPINVOKE.new_RakNetStatisticsStruct(), true) {
  }

}

}
