/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNetDotNet {

using System;
using System.Runtime.InteropServices;

public class RakNetworkFactory : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RakNetworkFactory(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(RakNetworkFactory obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~RakNetworkFactory() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        RakNetPINVOKE.delete_RakNetworkFactory(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public static RakPeerInterface GetRakPeerInterface() {
    IntPtr cPtr = RakNetPINVOKE.RakNetworkFactory_GetRakPeerInterface();
    RakPeerInterface ret = (cPtr == IntPtr.Zero) ? null : new RakPeerInterface(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_ConsoleServer GetConsoleServer() {
    IntPtr cPtr = RakNetPINVOKE.RakNetworkFactory_GetConsoleServer();
    SWIGTYPE_p_ConsoleServer ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_ConsoleServer(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_ReplicaManager GetReplicaManager() {
    IntPtr cPtr = RakNetPINVOKE.RakNetworkFactory_GetReplicaManager();
    SWIGTYPE_p_ReplicaManager ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_ReplicaManager(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_LogCommandParser GetLogCommandParser() {
    IntPtr cPtr = RakNetPINVOKE.RakNetworkFactory_GetLogCommandParser();
    SWIGTYPE_p_LogCommandParser ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_LogCommandParser(cPtr, false);
    return ret;
  }

  public static PacketLogger GetPacketLogger() {
    IntPtr cPtr = RakNetPINVOKE.RakNetworkFactory_GetPacketLogger();
    PacketLogger ret = (cPtr == IntPtr.Zero) ? null : new PacketLogger(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_RakNetCommandParser GetRakNetCommandParser() {
    IntPtr cPtr = RakNetPINVOKE.RakNetworkFactory_GetRakNetCommandParser();
    SWIGTYPE_p_RakNetCommandParser ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_RakNetCommandParser(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_RakNetTransport GetRakNetTransport() {
    IntPtr cPtr = RakNetPINVOKE.RakNetworkFactory_GetRakNetTransport();
    SWIGTYPE_p_RakNetTransport ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_RakNetTransport(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_TelnetTransport GetTelnetTransport() {
    IntPtr cPtr = RakNetPINVOKE.RakNetworkFactory_GetTelnetTransport();
    SWIGTYPE_p_TelnetTransport ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_TelnetTransport(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_PacketConsoleLogger GetPacketConsoleLogger() {
    IntPtr cPtr = RakNetPINVOKE.RakNetworkFactory_GetPacketConsoleLogger();
    SWIGTYPE_p_PacketConsoleLogger ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_PacketConsoleLogger(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_PacketFileLogger GetPacketFileLogger() {
    IntPtr cPtr = RakNetPINVOKE.RakNetworkFactory_GetPacketFileLogger();
    SWIGTYPE_p_PacketFileLogger ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_PacketFileLogger(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_Router GetRouter() {
    IntPtr cPtr = RakNetPINVOKE.RakNetworkFactory_GetRouter();
    SWIGTYPE_p_Router ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_Router(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_ConnectionGraph GetConnectionGraph() {
    IntPtr cPtr = RakNetPINVOKE.RakNetworkFactory_GetConnectionGraph();
    SWIGTYPE_p_ConnectionGraph ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_ConnectionGraph(cPtr, false);
    return ret;
  }

  public static void DestroyRakPeerInterface(RakPeerInterface i) {
    RakNetPINVOKE.RakNetworkFactory_DestroyRakPeerInterface(RakPeerInterface.getCPtr(i));
  }

  public static void DestroyConsoleServer(SWIGTYPE_p_ConsoleServer i) {
    RakNetPINVOKE.RakNetworkFactory_DestroyConsoleServer(SWIGTYPE_p_ConsoleServer.getCPtr(i));
  }

  public static void DestroyReplicaManager(SWIGTYPE_p_ReplicaManager i) {
    RakNetPINVOKE.RakNetworkFactory_DestroyReplicaManager(SWIGTYPE_p_ReplicaManager.getCPtr(i));
  }

  public static void DestroyLogCommandParser(SWIGTYPE_p_LogCommandParser i) {
    RakNetPINVOKE.RakNetworkFactory_DestroyLogCommandParser(SWIGTYPE_p_LogCommandParser.getCPtr(i));
  }

  public static void DestroyPacketLogger(PacketLogger i) {
    RakNetPINVOKE.RakNetworkFactory_DestroyPacketLogger(PacketLogger.getCPtr(i));
  }

  public static void DestroyRakNetCommandParser(SWIGTYPE_p_RakNetCommandParser i) {
    RakNetPINVOKE.RakNetworkFactory_DestroyRakNetCommandParser(SWIGTYPE_p_RakNetCommandParser.getCPtr(i));
  }

  public static void DestroyRakNetTransport(SWIGTYPE_p_RakNetTransport i) {
    RakNetPINVOKE.RakNetworkFactory_DestroyRakNetTransport(SWIGTYPE_p_RakNetTransport.getCPtr(i));
  }

  public static void DestroyTelnetTransport(SWIGTYPE_p_TelnetTransport i) {
    RakNetPINVOKE.RakNetworkFactory_DestroyTelnetTransport(SWIGTYPE_p_TelnetTransport.getCPtr(i));
  }

  public static void DestroyPacketConsoleLogger(SWIGTYPE_p_PacketConsoleLogger i) {
    RakNetPINVOKE.RakNetworkFactory_DestroyPacketConsoleLogger(SWIGTYPE_p_PacketConsoleLogger.getCPtr(i));
  }

  public static void DestroyPacketFileLogger(SWIGTYPE_p_PacketFileLogger i) {
    RakNetPINVOKE.RakNetworkFactory_DestroyPacketFileLogger(SWIGTYPE_p_PacketFileLogger.getCPtr(i));
  }

  public static void DestroyRouter(SWIGTYPE_p_Router i) {
    RakNetPINVOKE.RakNetworkFactory_DestroyRouter(SWIGTYPE_p_Router.getCPtr(i));
  }

  public static void DestroyConnectionGraph(SWIGTYPE_p_ConnectionGraph i) {
    RakNetPINVOKE.RakNetworkFactory_DestroyConnectionGraph(SWIGTYPE_p_ConnectionGraph.getCPtr(i));
  }

  public RakNetworkFactory() : this(RakNetPINVOKE.new_RakNetworkFactory(), true) {
  }

}

}
