/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNetDotNet {

using System;
using System.Runtime.InteropServices;

public class ServerNetworkIDGenerator : NetworkIDGenerator {
  private HandleRef swigCPtr;

  internal ServerNetworkIDGenerator(IntPtr cPtr, bool cMemoryOwn) : base(RakNetPINVOKE.ServerNetworkIDGeneratorUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ServerNetworkIDGenerator obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ServerNetworkIDGenerator() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        RakNetPINVOKE.delete_ServerNetworkIDGenerator(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public ServerNetworkIDGenerator() : this(RakNetPINVOKE.new_ServerNetworkIDGenerator(), true) {
  }

}

}
