/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNetDotNet {

using System;
using System.Runtime.InteropServices;

public class SystemAddress : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SystemAddress(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(SystemAddress obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~SystemAddress() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        RakNetPINVOKE.delete_SystemAddress(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public uint binaryAddress {
    set {
      RakNetPINVOKE.SystemAddress_binaryAddress_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.SystemAddress_binaryAddress_get(swigCPtr);
      return ret;
    } 
  }

  public ushort port {
    set {
      RakNetPINVOKE.SystemAddress_port_set(swigCPtr, value);
    } 
    get {
      ushort ret = RakNetPINVOKE.SystemAddress_port_get(swigCPtr);
      return ret;
    } 
  }

  public string ToString(bool writePort) {
    string ret = RakNetPINVOKE.SystemAddress_ToString__SWIG_0(swigCPtr, writePort);
    return ret;
  }

  public string ToString() {
    string ret = RakNetPINVOKE.SystemAddress_ToString__SWIG_1(swigCPtr);
    return ret;
  }

  public void SetBinaryAddress(string str) {
    RakNetPINVOKE.SystemAddress_SetBinaryAddress(swigCPtr, str);
  }

  public SystemAddress() : this(RakNetPINVOKE.new_SystemAddress(), true) {
  }

}

}
